### ISSUE TITLE
Command JX create user/jenkins user/jenkins token is confusing

### ISSUE THREAD

**Issue by sn00p** [jenkins-x/jx-docs#1039]
JX create user documentation looks confusing. 

Need a little bit more explanation what exactly jenkins user is from cli perspective. It's not the same as user in jenkins definitely. "Create a new User which is then provisioned by the user controller" explains almost nothing. 

This one is confusing too
https://github.com/jenkins-x/jx-docs/blob/master/content/commands/jx_create_jenkins_user.md
And it's not working because the actual command is 

╰─ jx create jenkins token -p somePassword someUserName
Please go to http://jenkins.jx.sn00p.silenkov.biz/me/configure and click Show API Token to get your API Token
Then COPY the token and enter in into the form below:

? API Token: 

Help from this cli command is confusing too because you can't click Show API Token in recent jenkins  version. You could only add a new token to the preexisting user, called admin in our case. 

So there is no way to add new user in jenkins via CLI, only via admin UI. It should be stated in documentation as there is a high demand operation to add not only tokens but  users in jenkins installation. 

Thanks,

**Comment by scaratec** [comment]
/remove-lifecycle rotten

Personally I must say, I can hardly find any explanation about what a user in the jenkins x context means. 

What I would like to understand is: 

- How can I segregate normal users/developers from the admin user?
- How can I actually login from another computer?
- How can I swith the user in respect to [PLOP](https://en.wikipedia.org/wiki/Principle_of_least_privilege)
