### ISSUE TITLE
Add JenkinsX roadmap page

### ISSUE THREAD

**Issue by gtseres** [jenkins-x/jx-docs#12]
When checking the [Features page](http://jenkins-x.io/about/features/), there was a link at the bottom pointing to the [Roadmap page](http://jenkins-x.io/about/features/contribute/roadmap/). Unfortunately, this page does not currently exist. It would be great if we could create such a page for people to be able to get information on the roadmap of the project.

**Comment by jstrachan** [comment]
@gtseres ah great catch thanks! should have a fix real soon...

**Comment by jstrachan** [comment]
@gtseres if you reload the page should link to the correct page now http://localhost:1313/about/features/#roadmap

**Comment by gtseres** [comment]
Yes, it's fixed now. Thanks @jstrachan !! 🎉
