### ISSUE TITLE
Broken links on jx-docs page

### ISSUE THREAD

**Issue by tushabe** [jenkins-x/jx-docs#14]
It appears all the links on [Feature.md](https://github.com/jenkins-x/jx-docs/blob/master/content/about/features.md) page are broken. I am not sure why.

**Comment by jstrachan** [comment]
@tushabe are you browsing the features page on the website: http://jenkins-x.io/about/features/ or in the source code markdown? 

The markdown links don't all work as they assume they are served inside the website. 

You can run `hugo serve -D` locally to try out the website if you want to edit things etc

**Comment by jstrachan** [comment]
I've just tried to polish the readme to make this a bit more clear hopefully https://github.com/jenkins-x/jx-docs/blob/master/README.md

**Comment by tushabe** [comment]
I was browsing it in the source code on github (here). I wasn't aware the same page existed the website. I will browse the link via the website. Thank you
