### ISSUE TITLE
Feature Request: Cover "Parts of Jenkins-x"

### ISSUE THREAD

**Issue by BenCoffeed** [jenkins-x/jx-docs#1526]
I would like to see a portion of the docs that breaks down the structure of Jenkins X. I wish I could provide a bulleted list of these, but unfortunately, I don't know them yet. The idea came from the fantastic new video by @sharepointoscar on custom builders. I realized that I wasn't aware of the actual role of a builder. So, I'd like to see terms like builders, pipelines, apps, applications, Prow, etc. and how they interact with each other and with your project.

**Comment by sharepointoscar** [comment]
Hi @BenCoffeed have you seen this? https://jenkins-x.io/architecture/components . There is a lot of info on the Architecture section too...

**Comment by sharepointoscar** [comment]
We are working to improve the entire site...
