### ISSUE TITLE
Use 'Delete merged branch' GitHub app

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#1632]
Use [Delete merged branch](https://probot.github.io/apps/delete-merged-branch/), a GitHub app that automatically deletes a branch after it's merged.

**Comment by shenxianpeng** [comment]
Yes, a lot of merge branch exist in current repo.

**Comment by MarckK** [comment]
Good find, @dennisnewel! 

That option is now selected. 😃
