### ISSUE TITLE
news missing from the new home page

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-docs#1867]
we used to have a News summary on the home page and a link to the news/blog page - its all gone now - lets try add it back?

**Comment by jstrachan** [comment]
https://jenkins-x.io/news/

**Comment by MarckK** [comment]
Hi @jstrachan, the link to the news/blog page is still in the top nav bar on the home page, but the name has been changed to 'Blog'. Nomenclature is hard -- it can be changed back to 'News' if you prefer.

The News / new blog posts summary section has been removed from the home page. This was decided on during the multi-phase redesign. A number of sections were taken out of the home page, as a way to tighten it up and focus a visitor's attention on what were decided to be the most important pieces of information. Again, everything is an iteration, so this can be added back in.

**Comment by jstrachan** [comment]
@MarckK aha sorry I missed the `Blog` link. Thanks for the heads up!

FWIW I've always found looking at OSS project home pages, I've liked some evidence of things changing; so showing a little bit of the news section - even if its near the bottom of the page - helps it look like things are happening on the project - too many OSS project home pages never seem to change which seems to imply lack of activity (lots of OSS projects are dormant). Though that might be just me and might not be a common reaction ;) 

Having a little line of recent news near the bottom (even just a few links) might help give the indication of change?

**Comment by jstrachan** [comment]
mind you having said that we're not always super active blogging (e.g. no news in August); so maybe just showing the latest release number + date somewhere might help show how fast the project moves?

**Comment by MarckK** [comment]
Great idea to show the latest release number + date! Excellent way to show how fast the project is moving. 😀

**Comment by MarckK** [comment]
We could have a link to latest blog post (or latest and penultimate), and brief info about each. 

I'm hesitant to start adding to the nice clean redesign, but one idea would be a narrow bar near the bottom with 3 info items: 

Latest release number + date             Latest blog post title                       Penultimate blog post title

Or something like that.

**Comment by jstrachan** [comment]
@MarckK that sounds great to me - something nice and concise that just shows the latest release number+date and latest blog post + date so its pretty compact and can be near the bottom to keep the first page nice and clean?

**Comment by MarckK** [comment]
Wdyt @sharepointoscar and @SarrahV?
