### ISSUE TITLE
Download does not exist

### ISSUE THREAD

**Issue by mcasperson** [jenkins-x/jx-docs#1884]
The instructions on https://jenkins-x.io/getting-started/install/ say to download the file from https://github.com/jenkins-x/jx/releases/download/latest/jx-linux-amd64.tar.gz. This file does not exist.

**Comment by dennisnewel** [comment]
I'll update the link. It shouldn't be a valid link as there's no option to link to a "latest" version on github (as far as i can tell) so you'll need to grab the correct URL from the https://github.com/jenkins-x/jx/releases/ page as mentioned above the link

**Comment by dennisnewel** [comment]
apparently there was a shortcode/command thingy to insert the latest version, so i used that instead. that should hopefully provide a correct link to the latest version

**Comment by dennisnewel** [comment]
this should be fixed now
