### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by pabloli84** [jenkins-x/jx-docs#1998]
This link in the Getting Started manual (https://jenkins-x.io/docs/getting-started/) leads to 404 page:

https://jenkins-x.io/docs/getting-started/install

**Comment by Hardik500** [comment]
I would like to solve this issue if there is no problem

**Comment by gemanepa** [comment]
@pabloli84 @MarckK how exactly would this issue be fixed for you? By replacing the link (for which one?) or by removing it?

**Comment by Hardik500** [comment]
@gemanepa  you have to replace the link with https://jenkins-x.io/docs/getting-started/setup/install/

**Comment by gemanepa** [comment]
@Hardik500 ok, I already found where to make the fix. I will make a PR in the next 24hs. Is there a way I can check locally if the fix was sucessful? The README.md doesn't have instructions about how to

**Comment by Hardik500** [comment]
To check it locally you need to install the build locally using the docs and make the changes there to check it.

**Comment by gemanepa** [comment]
Is there a step missing or something in "Start the Hugo server"? I'm having lots of errors in the building process. Starting with the {{% alert %}} & {{% pageinfo %}} in lots of files

![Screenshot from 2019-09-27 14-29-15](https://user-images.githubusercontent.com/36349751/65789306-81df7d80-e133-11e9-8fdd-74a1cd55b5f6.png)

![Screenshot from 2019-09-27 14-08-39](https://user-images.githubusercontent.com/36349751/65788203-f107a280-e130-11e9-80c1-a0ff9f4fe070.png)
![Screenshot from 2019-09-27 14-09-03](https://user-images.githubusercontent.com/36349751/65788218-f664ed00-e130-11e9-9544-7c7da38b6d15.png)

**Comment by MarckK** [comment]
Hi @gemanepa, thank you for your questions. We are currently improving the contributing guide, so your questions are timely and helpful. Improvements to the contributing guides are happening frequently atm, so please check back there and let us know what information you are finding incorrect or incomplete.

To build the site locally, are you using hugo (having installed hugo and running `hugo server`) or are you using the docker image?

Please note, for the change you are proposing you do not need to use the spellchecker and the linkchecker (that is an excessive amount of checking placed on you).

On the other hand, we do have a translation of the site, `中文`. You can view it as an option under the languages section (`English` in the top nav bar with a drop down menu). It would be fantastic of you to make your proposed link change to both the English and the `中文` versions of the site, similar to PR https://github.com/jenkins-x/jx-docs/pull/2010.

**Comment by ankingcodes** [comment]
@MarckK should I work on this or has it been assigned to someone else?

**Comment by MarckK** [comment]
@gemanepa, are you still working on this?

**Comment by gemanepa** [comment]
@MarckK no~
@ankingcodes go ahead

**Comment by sailesh97** [comment]
Is it still unsolved?

**Comment by ankingcodes** [comment]
@MarckK is [this](https://github.com/jenkins-x/jx-docs/blob/master/content/en/docs/getting-started/_index.md) where we need to make the change?

**Comment by chandanikumari** [comment]
@MarckK Is anyone working on this issue? or shall I ?

**Comment by MarckK** [comment]
As far as I know, no one else is working on it. Thank you, @chandanikumari :)

We do have a translation of the site, 中文. You can view it as an option under the languages section (English in the top nav bar with a drop down menu). It would be fantastic of you to make your proposed link change to both the English and the 中文 versions of the site, similar to PR #2010.

**Comment by dennisnewel** [comment]
i think this can be closed now
