### ISSUE TITLE
Building docs locally results in errors

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#2006]
Trying path as a new contributor to jx-docs and following instructions in README.md on how to work with the project. 

After `$ git clone  --recurse-submodules --depth 1 https://github.com/jenkins-x/jx-docs.git`, errors on step 2: `npm install`:

<img width="1464" alt="error" src="https://user-images.githubusercontent.com/15032115/65512223-b69fca80-ded0-11e9-9848-b4146617d0a4.png">

Looking over Docsy's instructions and they suggest running `hugo server` without an npm install. That resulted in a different category of errors relating to "taxonomy":

<img width="1581" alt="Screenshot 2019-09-24 at 13 42 25" src="https://user-images.githubusercontent.com/15032115/65512530-4d6c8700-ded1-11e9-8208-729cf6492890.png">

**Comment by dennisnewel** [comment]
i think we should remove the instructions to run hugo locally...there can be so many variations in people's setup and i think the docker-compose route is more fail-safe?

**Comment by MarckK** [comment]
We should definitely have instructions on how to build the site using a docker image. 

However, having that as our main -- or only -- way to build the site and contribute to the docs creates an unnecessarily high barrier to engagement. 

There should be no reason people can't run the site locally using `hugo server`. We should ensure that user path is available and working, hence this issue. 

I've augmented Getting Started instructions to make contributing more widely accessible: https://github.com/jenkins-x/jx-docs/pull/2014
(which is related to ensuring that contributing to the docs is as accessible as possible, but doesn't resolve this issue).

**Comment by MarckK** [comment]
Also, the instructions to build the docs site locally with a docker image are resulting in errors.

Following the current instructions, I run:

<img width="667" alt="Screenshot 2019-09-25 at 13 15 35" src="https://user-images.githubusercontent.com/15032115/65599918-dbf70c00-df96-11e9-98ef-cb2d379d2b8b.png">

Current instructions state that after running that command, "This will make the site available on http://localhost:1313/ and it will auto-update when you save changes to any of the files in the repo."

However, http://localhost:1313/ shows:
<img width="336" alt="Screenshot 2019-09-25 at 13 15 47" src="https://user-images.githubusercontent.com/15032115/65599997-11035e80-df97-11e9-9127-5fa40661720e.png">

**Comment by dennisnewel** [comment]
> However, having that as our main -- or only -- way to build the site and contribute to the docs creates an unnecessarily high barrier to engagement.

I'm not sure which is highest? getting hugo installed and running locally, or docker? Personally I feel docker is simpler as there are no special instructions/versions, but i could be biased by having worked in this way before.
My main concern is that we'd get all sorts of issues around hugo and setup, which is not necessarily related to the site. If we have one way that consistently works (i'll need to look into the docker issue you raised) i think that's a cleaner experience?

**Comment by dennisnewel** [comment]
Just realized i hadn't taken into account being able to update npm packages using the docker-compose approach. I've bumped the hugo image (dennisnewel/hugo-extended) to 0.58.3 which includes the latest hugo, but also changes it to be able to run other commands using the image.

It should be possible with that to run 
```sh
$ docker-compose run -w /src server npm install
```
to have it update the npm packages required by the site. 

Not sure that'll help your local issues though

**Comment by MarckK** [comment]
I bumped my hugo -- `hugo 0.55.6 -> 0.58.3`-- and running `hugo server` works to build the site locally for development.  

We should have both local development options outlined in the Contributing guidelines, e.g. running `hugo server` or building the site locally with a docker image. 

The Contributing guidelines can't just be limited to our preferred development workflow, in order to make the project accessible to the widest number of individuals.

**Comment by dennisnewel** [comment]
fair point. i'll see if i have time to setup something locally next week or so. if you're already up and running, would you be able to take a stab at it?
