### ISSUE TITLE
Build, test and preview an app TBD

### ISSUE THREAD

**Issue by etoews** [jenkins-x/jx-docs#2065]
The [Build, test and preview an app](https://jenkins-x.io/docs/getting-started/build-test-preview/) section needs to be completed.

**Comment by etoews** [comment]
Could be a good candidate for the `hacktoberfest` label.

**Comment by dennisnewel** [comment]
good call :) the main idea behind the section was to go through what it's like to make changes to your quickstart (e.g. add more logic + tests) and get the changes into a preview environment.

There just seems to be something missing between creating your quickstart and promoting an app to another environment

**Comment by jha-cloudbees** [comment]
I'm working on creating this article on the CJXD side with the intention on pushing the content back to the JX OSS docs. More to come soon!

**Comment by dennisnewel** [comment]
closing as the page now have actual content
