### ISSUE TITLE
Image in the Overview > Accelerate page links to missing page

### ISSUE THREAD

**Issue by mauromorales** [jenkins-x/jx-docs#2069]
The following image in the [Overview > Accelerate](https://jenkins-x.io/docs/overview/accelerate/) page points to "/about/accelerate" which is missing

![image](https://jenkins-x.io/images/capabilities.png)

**Comment by dennisnewel** [comment]
i'll add an alias for that url

in case you're interested, aliases are added by adding something like the following to the "front matter" section (i.e. the top meta-data on each page)

```
aliases:
  - /about/accelerate
```
