### ISSUE TITLE
[Question] jx boot - how to install default helm charts?

### ISSUE THREAD

**Issue by TarekAS** [jenkins-x/jx-docs#2096]
Not sure if this is in the scope of JenkinsX, but this what I'm trying to do.

When I run ```jx boot``` on a brand new cluster, I want it to automatically install a list of third party charts such as ```stable/prometheus``` with my custom values.

Is there a recommended way to do this? I have considered using **helmfile** but was wondering if JX already supports this.

**Comment by vfarcic** [comment]
You can add any additional charts to `env/requirements.yml` file and creating a directory with any additional charts. You can find quite a few examples in the `env` directory.

That being said, I suggest you do install Jenkins X first (using Boot) and then run the `jx add app` command. That will create all the files you need, plus a pull request, and a few other things.

**Comment by TarekAS** [comment]
Thank you for you feedback, it's great that JX supports this feature.
