### ISSUE TITLE
2 Layouts

### ISSUE THREAD

**Issue by butuzov** [jenkins-x/jx-docs#2120]
I was fixing broken links and found that site actually has two layouts

* https://jenkins-x.io/about/features/
* https://jenkins-x.io/about/

My guess first link was a previous design, and should be scraped. However, there are lot of the pages that refer to it (like `/about/features/`)

**Comment by dennisnewel** [comment]
you're right @butuzov /about/features is the old layout...i'm not 100% sure why those old pages haven't gone away. It's possible the deployment didn't first remove the old pages; i'll look into it

**Comment by butuzov** [comment]
Cause its generated and auto-committed as part o some deployment pipeline? (my best guess)

**Comment by dennisnewel** [comment]
pretty much. At the end of the pipeline we basically add any new generated files to the https://github.com/jenkins-x/jenkins-x-website which is the basis for the running site. It doesn't look like we take into account deleted/moved pages

**Comment by dennisnewel** [comment]
this should be fixed by #2235 which implements a process for removing old files before pushing a new version of the site

**Comment by dennisnewel** [comment]
this has now been fixed. Old pages are fully removed and will result in a 404 error
