### ISSUE TITLE
Move "Talks and Preferences" to the community sections

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/jx-docs#2132]
From @MarckK 

> We have a lot of talks listed in the "Talks and Conferences" section under "Getting Started" that don't have recordings of the talks. That page is mostly functioning as a calendar list of talks already given, some with brief abstracts.
> 
> This shows people are talking about Jenkins X and that the community is active, but isn't really useful for people looking for talks to help them with getting started. I propose moving this page to a "Talks and Conferences" section under community section. While leaving those talks that are recorded in this "Talks and Conferences" section, as useful resource for individuals looking for talks to watch to help them with getting started.

### Expected outcome
* Talks & Conferences page is moved into the community section
* A new page is created that focuses on getting help via watching talks
* Links to talks that were recorded are copied to the new page

**Comment by karentobo** [comment]
I'll give this a go for Hacktoberfest.

**Comment by dennisnewel** [comment]
thanks @karentobo! feel free to ping me if you run into issues :)
