### ISSUE TITLE
feat: Add link to newsletter archive

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/jx-docs#2135]
We already have an archive of the previous newsletter available online, it's just not a simple URL.

### Expected outcome
* there's a link on https://jenkins-x.io/community/ that points to https://us7.campaign-archive.com/home/?u=d0c128ac1f69ba2bb20742976&id=84d053b0a0

**Comment by xMateMCPE** [comment]
I'll take it

**Comment by dennisnewel** [comment]
thanks @xMate420x !

**Comment by dennisnewel** [comment]
we can close this now
