### ISSUE TITLE
Deprecated link in Getting Started section

### ISSUE THREAD

**Issue by mmorejon** [jenkins-x/jx-docs#2143]
Hi!
The page [Getting Started](https://jenkins-x.io/docs/getting-started/) have a link pointing to a deprecated file, specifically in this sentence:
If you already have an existing kubernetes cluster then [install Jenkins X on your kubernetes cluster](https://jenkins-x.io/docs/getting-started/install-on-cluster).

Exists an updated version of this section?

**Comment by dennisnewel** [comment]
That should probably point to using `jx boot` instead, right @jstrachan ?

**Comment by karentobo** [comment]
If that's the case, here's a fix and a bunch of copy edits because I live for apostrophes.
