### ISSUE TITLE
 File parameters.schema.json not found.

### ISSUE THREAD

**Issue by mmorejon** [jenkins-x/jx-docs#2149]
**Page:**
https://jenkins-x.io/docs/getting-started/setup/boot/how-it-works/

**Sentence:**
This uses the [parameters.schema.json](https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/env/parameters.schema.json) file which powers the UI.

**Comment by dennisnewel** [comment]
correct link seems to be https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/env/parameters.tmpl.schema.json
