### ISSUE TITLE
Different behavior for the same section

### ISSUE THREAD

**Issue by mmorejon** [jenkins-x/jx-docs#2205]
We can access to the following link without any problem, https://jenkins-x.io/docs/managing-jx/common-tasks/, then we can see the following elements:
access control, dns, security features, tls, upgrading jenkins x and create a custom link

![image](https://user-images.githubusercontent.com/5578317/68544428-6074e100-03c3-11ea-8bf9-4acc5f899de0.png)

But, and **this is the different behavior**, we can access to https://jenkins-x.io/docs/managing-jx/common-tasks/config/ and then we will see a complete different menu.

![image](https://user-images.githubusercontent.com/5578317/68544418-4affb700-03c3-11ea-9dfd-f1a86fbd4080.png)

**Comment by dennisnewel** [comment]
will close this as it seems to no longer be a problem. Not sure what would have caused that to occur though...

/close
