### ISSUE TITLE
Remove/Update "Install Jenkins X on GKE Properly" Tutorial 

### ISSUE THREAD

**Issue by skinlayers** [jenkins-x/jx-docs#2214]
The instructions in:
https://jenkins-x.io/docs/managing-jx/tutorials/jenkins-x-gke-install-with-bot/

Would seem to contradict the ones in:
https://jenkins-x.io/docs/getting-started/setup/boot/

To reduce confusion, could the "Install Jenkins X on GKE Properly" tutorial be remove or updated?

See https://app.slack.com/client/T09NY5SBT/C9MBGQJRH/thread/C9MBGQJRH-1573674068.410600 (#jenkinx-x-user slack channel)

Thank you!

**Comment by dennisnewel** [comment]
good point. It's probably best to remove the tutorial...i'll get a PR going for that

**Comment by dennisnewel** [comment]
waiting on #2235 to go through before implementing as the page would otherwise not be removed from the live site

**Comment by dennisnewel** [comment]
fixed
