### ISSUE TITLE
Build, test and preview an app

### ISSUE THREAD

**Issue by krishnaprasadkv** [jenkins-x/jx-docs#2223]
![image](https://user-images.githubusercontent.com/40483538/69048304-28a11580-0a23-11ea-87d8-747a34087703.png)

It looks like there is no content on this page.

**Comment by dennisnewel** [comment]
yeah, we've got this recorded as #2065 and @jha-cloudbees is working on it :) if you're interested in adding to the page i'm sure you can work together with John on it

**Comment by krishnaprasadkv** [comment]
Sure.

**Comment by dennisnewel** [comment]
#2065 is now closed since the page has been updated, so i'll close this issue as well
