### ISSUE TITLE
jx promote For more documentation see 404

### ISSUE THREAD

**Issue by woohgit** [jenkins-x/jx-docs#2243]
The link on the page https://jenkins-x.io/commands/jx_promote/  is 404

`For more documentation see: https://jenkins-x.io/about/features/#promotion` is a 404 link

**Comment by tomhobson** [comment]
Hi, I've made a collective pr here: https://github.com/jenkins-x/jx-docs/issues/2242
For all of the moved documentation.

**Comment by dennisnewel** [comment]
fixed
