### ISSUE TITLE
Cached link 404 https://jenkins-x.io/docs/managing-jx/tutorials/jenkins-x-gke-install-with-bot/

### ISSUE THREAD

**Issue by woohgit** [jenkins-x/jx-docs#2246]
Another 404

https://jenkins-x.io/docs/managing-jx/tutorials/jenkins-x-gke-install-with-bot/

**Comment by dennisnewel** [comment]
This was removed because the content had gotten old and out of date. Hopefully @sharepointoscar will have a chance to update the video some day, but for now we just took the page down

**Comment by dennisnewel** [comment]
i'll add an alias to send users to the tutorials page in general instead of the 404

**Comment by dennisnewel** [comment]
fixed
