### ISSUE TITLE
Move sponsors to the front page and add products built with JX

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/jx-docs#2265]
I know we've only got CloudBees as a sponsor right now, but i think it'd be good to show that there's someone backing the project and it might encourage others to join in as well :) 

Along side sponsors, we should show the product built with (or projects using) Jenkins X. There's a lot of work happening outside of JX that feeds a lot of fixes and improvements back into the project, so i think it's fair to show these off as well

**Comment by dennisnewel** [comment]
@MarckK @jstrachan @rawlingsj what do you think?

**Comment by jstrachan** [comment]
sounds good to me

**Comment by jstrachan** [comment]
we also should probably link to the CD.foundation site too

**Comment by dennisnewel** [comment]
good point. i'll try and put together a PR with the changes and include a prominent link to the CDF

**Comment by MarckK** [comment]
Sounds good.
