### ISSUE TITLE
Menu of top nav bar becomes limited as browser width decreases

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#2289]
At browser width of about 1090px, the top nav bar switches from:

<img width="1127" alt="Screenshot 2019-12-12 at 11 05 35" src="https://user-images.githubusercontent.com/15032115/70707197-8269c800-1ccf-11ea-862f-f996c6b9d221.png">

to:
<img width="1097" alt="Screenshot 2019-12-12 at 11 05 52" src="https://user-images.githubusercontent.com/15032115/70707248-a2998700-1ccf-11ea-883d-01d2adc7d646.png">

If would be better if we kept all the menu options in the top nav bar, even as the browser width decreases.

**Comment by JackieBinya** [comment]
@MarckK
To tackle the above issue I decided to redesign the navigation bar as shown in this [link](https://www.figma.com/file/LodrAG6V6D7JojdRkV6p1Y/JENKINSX?node-id=10%3A1) on figma.
*Description* 
* I decided to add a hamburger menu for small screens
* Onclick it reveals a drop down menu, with all the menu items in the large screen
Please review the design, if its satisfactory I then proceed with the implementation.
