### ISSUE TITLE
Create EKS cluster with Terraform

### ISSUE THREAD

**Issue by JoeNunnelley** [jenkins-x/jx-docs#2426]
this doc says to run jx install with parameters after the eks cluster comes up. But when I do that it tells me to use jx boot.  Jx boot does not take the parameters produced by the eks cluster terraform file provided by the site... What to do?

**Comment by hferentschik** [comment]
The bootstrapping process as well as the docs have changed. We recommend to use Terraform to create the EKS cluster and then run `jx boot` with the generated `jx-requirements.yml` file.

See also:

- https://jenkins-x.io/docs/getting-started/
- https://jenkins-x.io/docs/getting-started/setup/create-cluster/eks/
