### ISSUE TITLE
404 when accessing https://jenkins-x.io/docs/

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx-docs#2670]
After the restructure of the website https://jenkins-x.io/docs/ results now into a 404.

**Comment by ethangj** [comment]
@sharepointoscar will you look at this?

**Comment by hervelemeur** [comment]
The /docs/guides/ are also now returning a 404.

Example of a link from a websearch resulting in a 404 error: https://jenkins-x.io/docs/using-jx/pipelines/envvars/

The new link: https://jenkins-x.io/docs/guides/using-jx/pipelines/envvars/

**Comment by ethangj** [comment]
@hervelemeur thanks, I will get this resolved.

**Comment by sharepointoscar** [comment]
I think this issue can be closed?  @hferentschik @ethangj ?
