### ISSUE TITLE
Create a Docs SIG

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#2675]
## Goals
* Discuss documentation and docs issues for jenkins-x.io
* Review and coordinate documentation for new Jenkins X features
* Suggest improvements to user onboarding through better documentation on  jenkins-x.io
* Help community contributors get involved in Jenkins X documentation
* Content for the official Jenkins X blog
* Organize and revise technical content to improve UX and technical accuracy and keep content up to date, based on:

     * user-reported issues
     * content audits performed by SIG members

### Chairs
The Chairs of the SIG run operations and processes governing the SIG. They will also establish and decommission subprojects.

*TBD (see [comment below](https://github.com/jenkins-x/jx-docs/issues/2675#issuecomment-626840691))

### Proposed Subprojects
* Season of Docs

### Members
Membership to the SIG is open and we welcome new members to join!

## Contact
- [Open Community Issues/PRs](https://github.com/jenkins-x/jx-docs/issues)

## Meetings
* The Docs SIG meets every Monday at 16:30 UTC (*See your timezone [here](https://time.is/1630_in_UTC)*)
* Meetings will be recorded and made available on the [Jenkins X YouTube Channel](https://www.youtube.com/channel/UCN2kblPjXKMcjjVYmwvquvg)

**Comment by MarckK** [comment]
We should create a Subproject for each docs localization team / initiative.

Would this be of interested to you, @mmorejon and @LinuxSuRen?

**Comment by MarckK** [comment]
An additional goal for the SIG would be to outline minimum content for localization efforts. 

Localizing all of the Jenkins X documentation is an enormous task. It’s okay for localization teams / initiatives to start small and expand over time. The Docs SIG should create a list of minimum content to be covered in the initial effort.

**Comment by LinuxSuRen** [comment]
@MarckK Yes, I would be as part of this.

**Comment by MarckK** [comment]
Great to hear, @LinuxSuRen!

**Comment by MarckK** [comment]
Proposed Chair: @ethangj 
Proposed Working Groups / Subprojects and respective leaders:
* Content and Writing Quality: @jha-cloudbees 
* Structure of docs site: @sharepointoscar 
* 中文 translation: @LinuxSuRen 
* Spanish translation: @mmorejon 
* Season of Docs: @MarckK 

In addition, membership to the Docs SIG is open and we welcome new members to join!

**Comment by MarckK** [comment]
Woop! Steering Committee has unanimously agreed Docs SIG is an excellent idea.  🎉

See 12 May, 2020 [meeting notes](https://docs.google.com/document/d/1ZuMQxm4mYJP1x2vhZI6CgCxiLWWw6N6Um1bErKP1seE/edit#).

**Comment by MarckK** [comment]
[Docs SIG repo](https://github.com/jenkins-x/jx-community/tree/master/sig-docs) created 🎉
