### ISSUE TITLE
Need redirect for previous documentation landing page

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx-docs#2679]
When I attempt to browse to my pre-existing Jenkins X docs bookmark - https://jenkins-x.io/docs, I get a 404 page since the documentation site has been refactored.  I would minimally expect to be redirected to the new landing page - https://jenkins-x.io or the Getting Started page.

**Comment by ethangj** [comment]
Fixed with https://github.com/jenkins-x/jx-docs/pull/2682

**Comment by deanesmith** [comment]
This is happening again.

**Comment by ethangj** [comment]
Solved by https://github.com/jenkins-x/jx-docs/pull/2818
