### ISSUE TITLE
Cannot close Newsletter signup modal

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx-docs#2680]
When I am on the Jenkins X landing page I am prompted to sign up for the newsletter by a modal window.  Attempting to dismiss the modal using the X in the upper right hand corner.  Also, the modal window is not sized appropriately for the content and displays hortizontal and vertical scrollbars as a result.  

I am on Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by ethangj** [comment]
@sharepointoscar are we using the default mailchimp widget? i've noticed this problem also.

**Comment by sharepointoscar** [comment]
@ethangj yes, I copied and pasted the code snippet MailChimp provides.  I too am experiencing this sadly...

**Comment by ethangj** [comment]
I've changed it to be less intrusive, it works on most subpages but not the homepage. Probably some Javascript issue that we'll need to solve later.
