### ISSUE TITLE
The highlighted blue sections in Contribute documentation add no information

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#2685]
The two highlighted blue sections in [Contribute documentation section](https://jenkins-x.io/docs/contributing/documentation/) don't add any information.

The first section implied there is a guide to click through to, but this page is the guide on how to contribute to the documentation (and there is no link to any additional information). The second blue section has an incomplete sentence in it and implies information will be given which then isn't there.

See:

<img width="795" alt="Screenshot 2020-04-29 at 15 02 30" src="https://user-images.githubusercontent.com/15032115/80605203-a9c8f380-8a2a-11ea-9415-204b7058d0d7.png">

**Comment by sharepointoscar** [comment]
Ah, I see the problem.  It appears the be the link color within the **Info** type of Bootstrap element.  I'll take a look, as this may be the case across the entire site. @MarckK
