### ISSUE TITLE
Getting Started is biased

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx-docs#2716]
The [Get started](https://jenkins-x.io/docs/getting-started/) page gives an impression that JX works only in GKE and EKS. Please add a new tab "other" in "Step 1: Provision your Kubernetes Cluster" that would list the requirements for running `jx boot` in the platforms that are not covered with Terraform.

**Comment by MarckK** [comment]
Also, instructions for `jx create cluster` or even `jx install` on the docs site have been removed. But those instructions are still valid and that workflow still being used in workshops.
