### ISSUE TITLE
Improve Google Season of Docs project ideas list!

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#2726]
The [project ideas list for Season of Docs](https://jenkins-x.io/blog/2020/04/28/season-of-docs-2020/) could be improved and extended. See section [Project Ideas](https://jenkins-x.io/blog/2020/04/28/season-of-docs-2020/#project-ideas) in post.

We can continue to edit and improve the Project Ideas list through June.

The project ideas list includes documentation projects that we'd like a technical writer to tackle during this year's Season of Docs and will be read by technical writers who are considering contributing to the Jenkins X docs. It is in our interest to have a good project ideas list to help technical writers engage with our project. 

More information on creating good [GSoD Ideas for technical writing projects](https://developers.google.com/season-of-docs/docs/project-ideas)

Here is a short list of areas that we can think about suggesting for technical writers to work on:

* Refactor the open source project’s existing documentation to provide an improved user experience or a more accessible information architecture.
* Write a conceptual overview of, or introduction to, a product or feature. Often a team creates their technical documentation from the bottom up, with the result that there’s a lot of detail but it’s hard to understand the product as a whole. A technical writer can fix this.
* Create a tutorial for a high-profile use case.
* Create a set of focused how-to guides for specific tasks.
* Create a contributor’s guide that includes basic information about getting started as a contributor to the open source project, as well as any rules around licence agreements, processes for pull requests and reviews, building the project, and so on.

**Comment by MarckK** [comment]
Great to have you on board, @jha-cloudbees!  🎉Look forward to your suggestions and working with you on Season of Docs!

**Comment by ethangj** [comment]
Two proposals:

- In the pending left nav reorg, focus on the "Creating Projects" section. We would define 3-5 pages, some exist and some don't (Understanding Buildpacks, New Project With Quickstart Or Import, Defining Environments, etc) and have a writer work across the team to build out those pages

- Go through the Kubernetes Slack channel, closed issues, call reports, etc and define FAQs for common docs pages based on the questions we are able to resolve for the user with existing info or explanations
