### ISSUE TITLE
"Hashicorp Vault" should be replaced by "Banzaicloud Vault"

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-x/jx-docs#2771]
In this page https://jenkins-x.io/docs/reference/components/vault/, the vault quoted is still the Hashicorp one, but when running `jx boot` we can see it's the Banzaicloud one which is installed:

> Installing vault-operator operator with helm values: [image.repository=banzaicloud/vault-operator image.tag=0.5.3]

**Comment by hferentschik** [comment]
Fixed by pull request #2841
