### ISSUE TITLE
Example boxes in the documentation are unreadable

### ISSUE THREAD

**Issue by ascottix** [jenkins-x/jx-docs#2784]
### Summary
Example boxes in the documentation are unreadable

### Steps to reproduce the behavior
Open a page that contains an example, for example:
https://jenkins-x.io/docs/reference/components/pod-templates/

Go to the section "Referring to Pod Templates".

Check the boxed example.

### Expected behavior
The text in the example box should be readable.

### Actual behavior
The text in the example box is not readable because it contains very light text on a white background.

![Screen Shot 2020-05-14 at 16 05 40](https://user-images.githubusercontent.com/4243986/81950993-e8eb6d00-9604-11ea-821a-f9e6120b9865.png)

**Comment by ankitm123** [comment]
This is fixed by removing highlightjs and using chroma.

/close
