### ISSUE TITLE
Issues with Search and page links

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#2795]
When searching for information, such as signing off a commit, pages or links with the information appear as results under the search, but when you click on those results all lead to 404 page. :(

Using the signoff example, the documentation on signing off a commit is still [present in the documentation](https://jenkins-x.io/community/code/#signoff).

**Comment by hferentschik** [comment]
Is this still an issue? And how to you search? Are you talking about the internal Agnolia search or Google searches?

**Comment by MarckK** [comment]
Closing as search links are now leading to live pages, not 404s
