### ISSUE TITLE
Security page for Jenkins X is in the Community section, should be moved to main docs

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#2803]
[Security](https://jenkins-x.io/community/security/) would be more useful and make more sense as part of the main documentation.

**Comment by MarckK** [comment]
Wdyt, @ccojocar?

**Comment by ccojocar** [comment]
I think that it would be more helpful to have a link to these security page in the main page of https://jenkins-x.io/ site such that is visible to everyone.
