### ISSUE TITLE
Day of docs - Tuesday June 9th 2020

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx-docs#2824]
On Tuesday June 9th 2020 the first "JX Day of Docs" will be held.  JX Day of Docs is a concerted effort where engineers, technical writers, and community contributors take on Jenkins X documentation improvement efforts as their primary focus for the day.

For the initial Day of Docs we will leave it to participants to come up with their own documentation improvement task(s) and provide a comment in this issue as to what they'd like to do.  Any questions or concerns can be taken up in responses.

Some recommendations:
- Choose an area of the Jenkins X docs where you have some technical expertise and a reasonable understanding of what needs to be accomplished.  Keep in mind that readme.md files in Jenkins X repositories are also much in need of refinements.
- Review comments to this issue to ensure that you have not duplicated anyone else's proposal or you may wish to collaborate on a proposal with someone else if somebody has already proposed your idea.
- Comment on this issue what you would like to do and provide details and/or raise any questions

Potential candidates:
- Take a look at issues labeled with "docs-needed" in the JX repo for potential candidates ( https://github.com/jenkins-x/jx/issues?q=is%3Aopen+is%3Aissue+label%3Adocs-needed )  

- Challenges with `jx boot` is consistently an area that generates a large amount of community generated issues for Jenkins X, specifically where documentation shortcomings may not be available for a specific configuration ( see https://jenkins-x.io/docs/install-setup/installing/boot/ and https://jenkins-x.io/commands/jx_boot/)

We will likely leverage the dev public slack channel for collaboration on the 9th.

We look forward to your contributions!

**Comment by deanesmith** [comment]
My proposal for day-of-docs is to establish a "Jenkins X Capabilities Matrix".  The purpose of the matrix is to specify what features are known to work for which cloud providers.  The matrix can also include on-prem Kubernetes packages.  I will fill in the matrix for GKE since most features are known to work there then hoping for other's to help evolve and maintain the matrix over time.

I believe the benefits of having this matrix will help set expectations for users who are new to Jenkins X and to inspire community members to help us develop missing features for a specific platform where they may have greater expertise.

**Comment by hferentschik** [comment]
I'll start with finishing https://github.com/jenkins-x/jx-docs/pull/2645

**Comment by daveconde** [comment]
I'd like to improve the docs around the usage of TLS for user developed applications.

**Comment by daveconde** [comment]
Upgrade docs could also use some improvements.

**Comment by ankitm123** [comment]
I will try to remove some static jenkins related docs (from read me and jx docs website).

**Comment by mrageh** [comment]
I'd like to improve our docs around buildpacks, will involve a bit of learning :)

**Comment by jha-cloudbees** [comment]
I can work on the following structural issues:

* Rename "Creating Quickstarts" to "Quickstarts"
* Pulling "Import" from "Creating Quickstarts"
* Pushing "Build Packs" submenu to bottom of "Creating Projects"

Investigate and expose "Apps" section per @MarckK

**Comment by sharepointoscar** [comment]
I am finishing the initial diagrams that depict deployments in Kubernetes with Prow and Lighthouse, will be publishing these no later than tomorrow.

**Comment by MarckK** [comment]
I'd like to document the process of contributing a Jenkins X app. 

At the moment, I'd like advice/help specifically an adding a created App to Jenkins X apps repo. And I am happy to document this process.

**Comment by babadofar** [comment]
Regarding build packs,  consider renaming the Jenkins X build packs -they are easily confused with Cloud native buildpacks as defined here https://buildpacks.io/  While this perhaps can strictly not be considered to be documentation work, it is quite confusing.

**Comment by hferentschik** [comment]
I think we should also remove the 'Labs' section. Given that Labs is "closed" now, I am not sure what value this documentation still provides. Also, when searching for keywords, eg Vault, one gets hits in the main docs as well as in the Labs docs which is imo confusing.

**Comment by corinnekrych** [comment]
With @romainverduci we would like to contribute to add UI doc on quickstart/import which will be delivered in CJXD on June 26th RC

**Comment by mgoltzsche** [comment]
Enhance App documentation:
* Move https://github.com/cloudbees/jx-app-ui#development somewhere central or rather to the website (cc @MarckK, @jha-cloudbees)
* Document UI accessibility

**Comment by MarckK** [comment]
@deanesmith, Created an [Issue for further discussion](https://github.com/jenkins-x/jx-docs/issues/2844) based on your proposal for Capabilities Matrix.
