### ISSUE TITLE
Docs navigation

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx-docs#2869]
I suggest the following navigation structure for the left-hand menu:

* Concepts
  * What Is Jenkins X?
  * Lifecycle Of An Application
  * Best Practices As a Service
    * GitOps
    * ChatOps
    * Preview Environments
    * Cloud-Native
    * Kubernetes
* Setup
  * Getting Started (a quick demo setup in a few Cloud providers)
  * Infrastructure Setup
    * AWS
    * Azure
    * Google Cloud
    * OpenShift
    * Something else
  * Install
  * Upgrade
  * Reference
* Tasks
  * Create A New Project
  * Import An Existing Project
  * Manage Pull Requests
  * Promote To Environments
* Examples
* Operations
  * Configure TLS
  * Secrets Management
  * Logging
  * Reporting
* Reference

I believe that the proposed structure is self-explanatory. If it is not, it would mean that the structure is wrong, rather than that it requires additional explanation.

**Comment by hferentschik** [comment]
IMO we definitely need the concepts part back and another landing page into the docs. Right now there are concepts under "About" but that feels wrong.

**Comment by hferentschik** [comment]
https://istio.io/latest/docs/ could be an example/reference for a similar structure.

**Comment by deanesmith** [comment]
I am good with this.  There are deep assumptions in the Infrastructure Setup section that would require substantial effort.

**Comment by vfarcic** [comment]
@deanesmith Those are only example items. The final ones would certainly differ.

**Comment by sharepointoscar** [comment]
Not sure if **Operations** replaces **Guides** but I feel we still need a Guides section that has multiple real-world scenario configuration guidance.  

- How do I use my own SSL Certificates
- Bring my own Vault
- How do I give other developers access to the cluster, and why do I need to?
- How do I add users to Jenkins X for specific roles defined by Jenkins X?
- How do I harden my Jenkins X cluster

And the list goes on...

**Comment by ankitm123** [comment]
Would be nice to have a production hardening sub-section under operations (similar to what hashicorp has: https://learn.hashicorp.com/vault/operations/production-hardening)

**Comment by sharepointoscar** [comment]
> Would be nice to have a production hardening sub-section under operations (similar to what hashicorp has: https://learn.hashicorp.com/vault/operations/production-hardening)

Exactly @ankitm123 , this is the last bullet I added above.
