### ISSUE TITLE
Modify jx version and jx diagnose docs

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx-docs#2880]
There was a recent change to version and diagnose command, This should be documented.
https://github.com/jenkins-x/jx/pull/7092

**Comment by hferentschik** [comment]
I guess technically in the cases where `jx version` is used in the docs it won't matter much whether you run `jx version` vs `jx version --short`. But the latter is probably the "nicer" to use if you literally just want the jx version or basically test whether `jx` is on the PATH.

**Comment by ankitm123** [comment]
`jx --version` used to print out only the version of the binary, and `jx version --short` does the same. As you mentioned, a nicer and less confusing way to quickly test.
