### ISSUE TITLE
Restructure "Install and Setup"

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx-docs#2894]
Currently, we have a sort of duplication in the left side navigation with having "Install and Setup" and then as a sub-menu "Install Jenkins X". That feels odd. 

<img width="1100" alt="Screenshot 2020-06-18 at 10 14 55" src="https://user-images.githubusercontent.com/296354/84995762-b0cbd280-b14c-11ea-8f0d-7bf5bc0bc643.png">

I think the reason for that is that "Install and Setup" contains more than it needs to. There is already an issue to move the SCM config docs #2884. After that, it is only "Install Jenkins X" and "Upgrade Jenkins X" left. 

For me "upgrading" is not an "install and setup" task. I suggest having a dedicated "Task" menu item under which to move the "Upgrade Jenkins X". Other tasks to follow. Something like that:

<img width="326" alt="Screenshot 2020-06-18 at 10 20 28" src="https://user-images.githubusercontent.com/296354/84996313-5f701300-b14d-11ea-8b87-732b1c8b8860.png">

After that there is only "Install Jenkins X" left under "Install and Setup" and we can remove one intermediate level.

**Comment by hferentschik** [comment]
We can then decide what the item should be called - "Install", "Setup" or "Install and Setup".

**Comment by ethangj** [comment]
What all would go in Tasks?

**Comment by hferentschik** [comment]
> What all would go in Tasks?

Upgrading jx, creating teams, creating environments, creating build packs, using dev pods - mainly user/dev centric

I could imagine a split between "admin" and "dev" tasks.

**Comment by hferentschik** [comment]
Closing this one, since install got refactored in #2919 

The task idea is still there, but we can track this separately.
