### ISSUE TITLE
Code snippet boxes need to be scrollable 

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx-docs#2924]
Some longer lines in example commands/scripts render badly due to the fact that the code boxes are not scrollable.

<img width="1111" alt="Screenshot 2020-06-25 at 17 12 00" src="https://user-images.githubusercontent.com/296354/85746780-ff5a0d80-b706-11ea-8f7c-f071fffc63e1.png">

The line breaking makes it hard to understand the content in this example

**Comment by borntorock** [comment]
With the usage of prism module, we now have the scrollable as well as copy option in code blocks. 

Code snippets present in this link: `https://jenkins-x.io/docs/install-setup/boot/secrets/` are understandable and in single lines. 

hence, closing this issue. 

@hferentschik feel free to open a new issue or re-open this issue if you find any code snippet line in multiple lines.
