### ISSUE TITLE
Create GKE cluster - Prerequisites missing

### ISSUE THREAD

**Issue by davidjsanders** [jenkins-x/jx-docs#2953]
When running the terraform script on a new GCP project, I forgot to enable the Kubernetes API. As expected, the apply bombed out with a 403 `Kubernetes Engine API is not enabled for this project`. It would be helpful if the documentation could be updated to explicitly call out the APIs required to be enabled or enable them as resources in the tf module?

**Comment by borntorock** [comment]
@davidjsanders Could you mention which terraform script were you using on a new GCP project? Was it for Jenkins X version 2 or 3. 

Also, which part of the documentation were you referring to, while running JX on GCP.

**Comment by ankitm123** [comment]
@borntorock this is already fixed by this PR: https://github.com/jenkins-x/terraform-google-jx/pull/125. You can close this issue.
