### ISSUE TITLE
Jenkins X Capabilities Matrix - AKS missing

### ISSUE THREAD

**Issue by dbroeglin** [jenkins-x/jx-docs#2965]
I was looking at https://jenkins-x.io/about/capabilities/ and was surprised not to see information for AKS despite the fact that it is documented here https://jenkins-x.io/docs/resources/guides/managing-jx/old/create-cluster/#using-azure-aks 

Disclaimer: I'm a Microsoft employee ;-) Is there something we could do to help?

**Comment by ankitm123** [comment]
@dbroeglin recently lot of work is being done to create a terraform module by @chrismellard: https://github.com/jenkins-x/terraform-azurerm-jx. 
This is the project board for the jx aks integration: https://github.com/orgs/jenkins-x/projects/9.
I believe @helayoty is the person who is leading the effort.

Atm, only gke and eks integrations have been tested, aks support in jx is not there yet (hence it's missing from the matrix).

PS: Would be awesome if more contributions came for aks integration :). The corresponding issue tracker for aks is here: https://github.com/jenkins-x/jx/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Faks

**Comment by chrismellard** [comment]
This is work in progress and I'm working on bits and pieces here and there to get AKS operational (currently Velero support). I have an operational AKS cluster locally from terraform/boot but the rate of PR review isn't getting these changes reviewed and/or merged. I'll try nudge these along.

**Comment by helayoty** [comment]
@dbroeglin Happy to see more people from MS :) I would really appreciate if you can create an issue with the requirement you'd like to see so we can prioritize. And we'll be so happy if we have more folks to contribute as well so we can move faster :)

**Comment by dbroeglin** [comment]
@helayoty I did not have any specific requirement in mind except my question at the top of the thread. I was actually relaying the question of one one of my customers and you answered it thoroughly. Thanks a lot!

As for contributions, I will look into the board and see if I can contribute something meaningful. I have a bit of time I usually allocate to OSS development and  would love to help along. I guess I could start with testing the current version and updating the Capabilities Matrix.

**Comment by borntorock** [comment]
We do now have AKS mentioned in the Jenkins X Maturity Level / Capabilities matrix for the v3.x Alpha version. https://jenkins-x.io/docs/v3/about/maturity-matrix/

The matrix would be updated for the upcoming release of Jenkins X, probably the Jenkins X v3.x beta version. 

I think we can close this issue. @rawlingsj @jstrachan  what do you think?

**Comment by MarckK** [comment]
Closed due to https://jenkins-x.io/docs/v3/about/maturity-matrix/.
