### ISSUE TITLE
Broken links: how to build

### ISSUE THREAD

**Issue by jcarsique** [jenkins-x/jx-docs#2969]
At the bottom of https://jenkins-x.io/docs/install-setup/install-binary/ page, the "build it yourself" link is broken
Replace https://github.com/jenkins-x/jx/blob/master/docs/contributing/hacking.md 
with https://github.com/jenkins-x/jx/blob/master/CONTRIBUTING.MD

**Comment by ankitm123** [comment]
I think this is the correct link: https://jenkins-x.io/community/code/, good catch :+1: 
Also not sure why the htmlproofer does not catch this, will check.
