### ISSUE TITLE
JX docs pr-build failing due to html proofer errors on files being pulled in from external repos

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#2970]
Logs showing pr-build failure: 

<img width="803" alt="Screenshot 2020-07-21 at 12 49 26" src="https://user-images.githubusercontent.com/15032115/88055574-231e4100-cb57-11ea-9416-5e430dcff720.png">

The[ labs/enhancements directory](https://github.com/jenkins-x/jx-docs/tree/master/content/en/community/labs) now point to [jx/enhancements repo](https://github.com/jenkins-x/enhancements/tree/ef821c2aa8063e15c2356b41faa8a19e47b58975). And within that repo some of the proposals point to repos external to jx org. This makes it difficult to fix html-proofer errors, etc.

**Comment by ankitm123** [comment]
This was already fixed, closing this @MarckK 

/close
