### ISSUE TITLE
On the page https://jenkins-x.io/commands/jx_create_branchpattern/

### ISSUE THREAD

**Issue by vlad-bura** [jenkins-x/jx-docs#2974]
https://jenkins-x.io/docs/using-jx/creating/import/#branch-patterns invalid URL

**Comment by ankitm123** [comment]
How did you reach that page? I dont see a link to it in the docs page.

**Comment by ankitm123** [comment]
So it comes from here: https://jenkins-x.io/commands/jx_create_branchpattern/ 
@MarckK found it :+1:
