### ISSUE TITLE
Document new jenkinsX UI

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx-docs#2976]
We have a new open source UI for jenkinsX, which is based on octant. There will be a demo by @jstrachan in the next office hours on it. 
We should document it, so that users of jenkinsX will start using it rightaway.
https://github.com/jenkins-x/octant-jx

**Comment by jstrachan** [comment]
we've got these docs now https://jenkins-x.io/docs/v3/guides/ui/
