### ISSUE TITLE
 should I create pv before  run " jx install --provider=kubernetes --on-premise"

### ISSUE THREAD

**Issue by rhinoceros** [jenkins-x/jx-docs#303]
after I ran install-command-line,
```jx install --provider=kubernetes --on-premise```
I found that all pvc were pending

```

root@172-18-23-101:~/xxx# kubectl get pvc
NAME                        STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
jenkins                     Pending                                                      4m
jenkins-x-chartmuseum       Pending                                                      4m
jenkins-x-docker-registry   Pending                                                      4m
jenkins-x-mongodb           Pending                                                      4m
jenkins-x-nexus             Pending                                                      4m
root@172-18-23-101:~/xxx# kubectl get pvc
NAME                        STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
jenkins                     Pending                                                      4m
jenkins-x-chartmuseum       Pending                                                      4m
jenkins-x-docker-registry   Pending                                                      4m
jenkins-x-mongodb           Pending                                                      4m
jenkins-x-nexus             Pending                                                      4m
```

**Comment by rawlingsj** [comment]
Do you have a cluster storage class?  If not try adding one that works with your storage solution https://kubernetes.io/docs/concepts/storage/storage-classes/  then the PVCs should bind to a PV.

**Comment by rhinoceros** [comment]
OK,  I found the problem ,and then create those five PVs. 
```
jenkins                    
jenkins-x-chartmuseum      
jenkins-x-docker-registry  
jenkins-x-mongodb          
jenkins-x-nexus            
```
I want to say, may be we should update the installation document add pre-requirement before run : 
`jx install --provider=kubernetes --on-premise`

**Comment by hgd2018** [comment]
Hi, can share light how to create the PV's, 

I am using this .yaml, but looks like it's not working.I am planning to install jenkinsx same server with kubernetes master.

kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins
  labels:
    type: local
spec:
  storageClassName: jenkins
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jenkins"

Is there anything I am doing wrong?
