### ISSUE TITLE
Getting Started With GKE

### ISSUE THREAD

**Issue by tgelpi-gmail** [jenkins-x/jx-docs#3044]
Document page: https://jenkins-x.io/docs/v3/getting-started/gke/
When trying to create a Git repo from this page using the link "https://github.com/jx3-gitops-repositories/jx3-gke-terraform-vault/generate" it generates a 404. It looks like you have to be logged into Git in the browser prior to using the link.

**Comment by ankitm123** [comment]
Good point, should be mentioned in the docs. You need a github account initially to start the process. After you have cloned it, you can change the remote-url to point to bitbucket or gitlab.

**Comment by borntorock** [comment]
@ankitm123 Looks like a note is already mentioned on this page https://jenkins-x.io/docs/v3/getting-started/gke/. 

Do you think any other information to be mentioned as part of this issue?

**Comment by borntorock** [comment]
@ankitm123 Could you Please update on this, last note?

**Comment by ankitm123** [comment]
I think it's safe to close this issue, the note makes sense.
