### ISSUE TITLE
Doc Versioning

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#3048]
**This is a Feature Request**

**What would you like to be added**

Doc Versioning. 

Docsy makes it easy to do doc versioning, including the ability to display a banner on archived doc sites/versions: https://www.docsy.dev/docs/adding-content/versioning/

**Why is this needed**

To differentiate Jenkins X 3 docs from Jenkins X 2 docs.

**Comments**

This isn't an immediately pressing issue, but as Jenkins X 3 matures, it will be helpful and clarifying if the docs are versioned.

**Comment by borntorock** [comment]
A reference example of docsy docs for versioning is [Kubeflow docs](https://www.kubeflow.org/docs/about/kubeflow/) which has no box mentioning on the stable docs built from v1.1 or master branch but for other versions in dropped down option a box appears on almost all webpages displaying something like this:

```
Version v0.7 of the documentation is no longer actively maintained. The site that you are currently viewing is an archived snapshot. For up-to-date documentation, see the latest version.
```

Link: https://v0-7.kubeflow.org/docs/

The source code of the Kubeflow docs is present [here](https://github.com/kubeflow/website).
