### ISSUE TITLE
add a copy button to code examples

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#3049]
**This is a Feature Request**

**What would you like to be added**

Code examples in tutorials, READme files, and guides could use a copy button so people don't miss a single thing when they copy code.

**Why is this needed**
Better user experience.

**Comments**

Once this PR, https://github.com/google/docsy/pull/325, is merged Jenkins X docs should be able to add copy button to code examples quite easily. 🤞

**Comment by MarckK** [comment]
Prism support has been added to Docsy. 🎉

@borntorock, Would you like to work on this issue?

**Comment by borntorock** [comment]
> @borntorock, Would you like to work on this issue?

Yeah, happy to work on this issue.
