### ISSUE TITLE
Validate the Jenkins X v3 docs on GKE

### ISSUE THREAD

**Issue by borntorock** [jenkins-x/jx-docs#3062]
**This is a Bug Report**

**Problem:**
Validate the technical steps mentioned in Jenkins X v3 docs for GKE. 
* For creating Jenkins X cluster on Google Cloud (readme terraform repo)
* Sections present in Guides. 

**Proposed Solution:**

**Page to Update:**
https://jenkins-x.io/docs/v3/

v3

**Comment by viveksahu26** [comment]
Hey @borntorock , is this issue for beginners.. I will like to try it.  Can you assign me..

**Comment by borntorock** [comment]
@viveksahu26 I'm on this issue. Try looking at issues labelled "good first issue" and "hacktoberfest".

**Comment by viveksahu26** [comment]
@borntorock  ok.. but I can do it.. Should I try..
