### ISSUE TITLE
Site reorganization for v2 and v3

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx-docs#3082]
**This is a Feature Request**
It would be helpful for jx users if they know which page talks about jx3 and which ones talk abt jx2 (or below). 
For example (terraform):
![image](https://user-images.githubusercontent.com/6242296/94931969-6de10100-0496-11eb-861e-bbfd251164df.png)

**What would you like to be added**
A v2 directory should be added, the same way we have a v3. For things that are the same across v3 and v2, we can have a shared folder (?)
A banner clearly showing that this page talks about jx3 and beyond (or jx2 and lower).

**Why is this needed**
This will avoid confusions for new users when they start using jx.

**Comment by borntorock** [comment]
Almost similar in comparison to this Issue on Doc Versioning https://github.com/jenkins-x/jx-docs/issues/3048

**Comment by ankitm123** [comment]
@borntorock I think this is exactly the same as #3048. Going to close this.

/close
