### ISSUE TITLE
Minikube

### ISSUE THREAD

**Issue by papadpanais9** [jenkins-x/jx-docs#3112]
I followed the instructions from here: https://jenkins-x.io/docs/v3/guides/infra/minikube/ but on setup step it only mentions the following
Create Git Repository to store the GitOps configuration of Jenkins X and the apps you want to deploy.
I think the documentation should also mention that you should initialize the repository from the `jx3-minikube-vault ` repository.

**Comment by hervelemeur** [comment]
In this documentation, "Create Git Repository" is already a button with a link to generate a repository from jx3-minikube-vault: https://github.com/jx3-gitops-repositories/jx3-minikube-vault/generate

**Comment by jstrachan** [comment]
hopefully the docs are more clear now
