### ISSUE TITLE
Help people more with Semantic Pull Requests (or remove the requirement)

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#3116]
**This is a Feature Request**

**What would you like to be added**

First time PRs are hitting a road block due to our semantic pull request rules. Either we need to give more and clearer instructions on semantic pull requests or remove the requirement. 

**Why is this needed**
Having new contributors trip over this doesn't help with the on-boarding of new contributors. 

**Comments**

Trying to help move a PR forward by leaving messages on PRs blocked due to semantic pull request rules isn't efficient. And it isn't a good new contributor experience.

Examples:
https://github.com/jenkins-x/jx/pull/7499
https://github.com/jenkins-x/jx-docs/pull/3111
https://github.com/jenkins-x/jx-docs/pull/3097
https://github.com/jenkins-x/jx-docs/pull/3093
https://github.com/jenkins-x/jx-docs/pull/3092

**Comment by borntorock** [comment]
@MarckK other suggestion for this would be to create a Pull Request template (similar to the one created for github Issue Template) mentioning the instructions / requirements for submitting the PR. This will enable the submitter to notice the instructions and follow before submitting the PR for review. 

Let me know, if this sounds good to you. I can submit a PR for this then.

**Comment by borntorock** [comment]
As per the latest discussion, keeping this issue on hold, as the semantic PR checks is being configured on the `jenkins-x` org. Disabling it would disable for all the repos in the `jenkins-x` org. 

Suggestion from @rawlingsj to may be create a new org for docs / website stuff.

**Comment by MarckK** [comment]
> @MarckK other suggestion for this would be to create a Pull Request template (similar to the one created for github Issue Template) mentioning the instructions / requirements for submitting the PR. This will enable the submitter to notice the instructions and follow before submitting the PR for review.
> 
> Let me know, if this sounds good to you. I can submit a PR for this then.

@borntorock, Given [discussion during yesterday's Docs SIG meeting](https://github.com/jenkins-x/jx-community/blob/master/sig-docs/meetings.md#agenda-and-notes-1) that we would not remove the semantic PR requirement for the docs repo, as it is configured org wide, would you like to create the GitHub Issue template that you've suggested above?

**Comment by borntorock** [comment]
@MarckK we already have the Github issue template but not the PR template. Let me know if we do need to have the template for Github PRs.

**Comment by MarckK** [comment]
@borntorock Yes! The GitHub PR template was indeed what I meant. :)
