### ISSUE TITLE
The Maturity Matrix is missing Openshift on Premise

### ISSUE THREAD

**Issue by manuelwallrapp** [jenkins-x/jx-docs#3125]
Hi 

I really like the maturity Matrix. I miss there Openshift on Premise. Thank you for the work. It's visible what is missing. 

Cheers.. Manu

**Comment by borntorock** [comment]
@manuelwallrapp Regarding your query, we have included OKD 4 (latest version of OpenShift) either on premise or on cloud, in the maturity level matrix for reference.
