### ISSUE TITLE
Multi-Cluster - jx project import --url 

### ISSUE THREAD

**Issue by adrianiacob22** [jenkins-x/jx-docs#3233]
When running jx project import command in order to setup a remote cluster, for staging environment, I believe it must be specified that the command should be executed from a different directory than development environment directory, because that command is cloning the staging repository inside development directory.

**Comment by jstrachan** [comment]
I've just polished the [how to setup multi cluster](https://jenkins-x.io/v3/admin/guides/multi-cluster/multi-cluster/) docs to hopefully make that much more clear - thanks!
