### ISSUE TITLE
How to disable jenkins-x 3 components

### ISSUE THREAD

**Issue by adrianiacob22** [jenkins-x/jx-docs#3234]
**This is a Bug Report**
Yes

**Problem:**
In Multi Cluster setup documentation there is no explanation on how certain components can be disabled

**Proposed Solution:**
Please update the documentation explaining better how can some components of Jenkins X can be disabled when creating another environment repository.

    Lighthouse
    Tekton
    Webhooks
    Nexus / Bucketrepo

**Page to Update:**
https://jenkins-x.io/docs/....

**Steps to Reproduce:**

Jenkins X 3.1.258

**Comment by jstrachan** [comment]
we've just polished the docs on [how to setup multi cluster](https://jenkins-x.io/v3/admin/guides/multi-cluster/multi-cluster/)

We've got a repository with a cut down pre-prod / production cluster: https://github.com/jx3-gitops-repositories/jx3-kubernetes-production which has the development services (tekton, lighthouse, nexus etc) removed
