### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by rajatgupta24** [jenkins-x/jx-docs#3313]
**This is a Bug Report**
Hey, I was going through the site & I noticed that the site is not mobile-friendly at all.

**Problem:**
![image](https://user-images.githubusercontent.com/55191777/115599866-af81ae00-a2f9-11eb-8699-0040e48fd460.png)

**Proposed Solution:**
I'd like to work on the mobile view of the site to make it mobile-friendly using the media queries.

**Page to Update:**
https://jenkins-x.io/docs/....

**Steps to Reproduce:**
Visit: https://jenkins-x.io/ 
(on mobile)

**Comment by rajatgupta24** [comment]
Hey @jstrachan, can I start working on it?

**Comment by amino19** [comment]
@rajatgupta24 : Shall I work on this?
