### ISSUE TITLE
docs don't reflect code

### ISSUE THREAD

**Issue by bmcgair** [jenkins-x/jx-docs#3385]
make the documentation correspond to the actual code. For example:

~/GitHub/cluster$ jx boot
Error: unknown command "boot" for "jx"

~/GitHub/cluster$ jx step verify install
Error: unknown command "step" for "jx"

**Comment by hervelemeur** [comment]
Where did you see that? Are you sure you're on the jx3 doc version and not on the jx2 one?

**Comment by jstrachan** [comment]
I guess you were looking at old v2 docs - see the v2 doc warning on v2 docs in the breadcrumbs
