### ISSUE TITLE
Suggested correction for a typo.  The word "how" should be "now".

### ISSUE THREAD

**Issue by proth1** [jenkins-x/jx-docs#3426]
Following is the text snippet:

Preview environments **how** use helmfile as

**Comment by AnirudhPanda** [comment]
Is this for hacktoberfest? or how can I reproduce this?

**Comment by ankitm123** [comment]
> how can I reproduce this?

@AnirudhPanda the typo is here: https://github.com/jenkins-x/jx-docs/blob/main/content/en/v3/about/changes.md?plain=1#L66
To build the docs locally, look at the contribution guide: https://jenkins-x.io/community/documentation/#docker-compose-method

> Is this for hacktoberfest?

I dont have an answer for it. @rawlingsj wdyt?

**Comment by ankitm123** [comment]
@AnirudhPanda go ahead with the contribution! I added the label for it ...
