### ISSUE TITLE
Discourse forum does not exist

### ISSUE THREAD

**Issue by abitrolly** [jenkins-x/jx-docs#3473]
**This is a Bug Report**

**Problem:**

![image](https://user-images.githubusercontent.com/8781107/139391266-3b913d02-ae4b-4bbe-85b6-eaf239302987.png)

**Steps to Reproduce:**

https://jenkinsx.discourse.group/

Ref. https://github.com/jenkins-x/jx/issues/7044

**Comment by ankitm123** [comment]
Not sure, when it was taken down. We should remove it from the docs. We are very active in slack, and use github issues.
