### ISSUE TITLE
Failed to find the dev Environment

### ISSUE THREAD

**Issue by galaxyNeha** [jenkins-x/jx-docs#3476]
>> jx project mlquickstart
error: failed to validate options: failed to find the dev Environment: Get "https://192.168.49.2:8443/apis/jenkins.io/v1/namespaces/jx-git-operator/environments?labelSelector=env%3Ddev": dial tcp 192.168.49.2:8443: connect: no route to host

**Comment by ankitm123** [comment]
Closing this, as mentioned in slack, this is resolved now.
/close
