### ISSUE TITLE
Docs explaining real world scenarios

### ISSUE THREAD

**Issue by sidkris77** [jenkins-x/jx-docs#3479]
**This is a Feature Request**

**What would you like to be added**
It would be great if the docs explain real world scenarios like integrating security scanners like Clair/Trivy/Anchore. Including other micro services in a preview environment as part of an integration test. Unfortunately could find no documentation on these. There seems to be no books on JenkinsX v3 or courses. Quite a few using v2. The main docs doesn’t go into detail. Love the approach of JenkinsX but the lack of docs is frustrating. A few bugs in the catalogs like maven-quarkus and the repo for EKS I was able to resolve but a trial and error way forward is really painful. Something like a Jenkins-X 101 would be awesome.

**Why is this needed**
Evaluating JenkinsX for a new AI SaaS product as JX seems to eliminate a lot of plumbing. This would be deployed on Amazon EKS. 

**Comments**
Any advice would be appreciated.

**Comment by ankitm123** [comment]
> It would be great if the docs explain real world scenarios like integrating security scanners like Clair/Trivy/Anchore

We can add docs on that, it would most probably be a task in the jx3-pipeline-catalog repository.

> The main docs doesn’t go into detail

Can you open few issues around those? I can try to fill in the gaps (or triage it, and ask people in the community who know the most about it to contribute).

> the repo for EKS I was able to resolve

Can you point me to the issues with EKS?

**Comment by sidkris77** [comment]
1) Does not seem to work with K8S version 1.21 so used 1.20.

2) The only Terraform eks-jx version that worked for me was 1.15.37. The ref in the source doesnt work so removed it.

```
module "eks-jx" {
  source                          = "jenkins-x/eks-jx/aws"
  version                         = "1.15.37"
```

3) The EKS vault chart points to a non-existant vault-instance repo. Had to manually modify it to the one below.

.terraform/modules/eks-jx/modules/vault/charts.tf

```
resource "helm_release" "vault-instance" {
  count      = local.create_vault_resources ? 1 : 0
  name       = "vault-instance"
  chart      = "vault-instance"
  namespace  = "jx-vault"
  repository = "https://jenkins-x-charts.github.io/repo"
  version    = "1.0.22"
  depends_on = [helm_release.vault-operator]
}
```

**Comment by sidkris77** [comment]
Thanks. Raised an issue here: https://github.com/jenkins-x/jx3-pipeline-catalog/issues/929

**Comment by ankitm123** [comment]
> Does not seem to work with K8S version 1.21 so used 1.20

If you are using vault, then we have to wait for these 2 PRs to be merged: https://github.com/jenkins-x-charts/vault-instance/pull/12 and https://github.com/jenkins-x/terraform-aws-eks-jx/pull/320
If you are not using vault, and still seeing issues with 1.21, I would like to know what the issue is. 

> The only Terraform eks-jx version that worked for me was 1.15.37. The ref in the source doesnt work so removed it.

Yes, that ref is being appended, and I am not sure where it's coming from, I will see how to fix that. But you should use the latest version of tf module.

>The EKS vault chart points to a non-existant vault-instance repo. Had to manually modify it to the one below.

Yes, the latest version fixes that (actually few versions before the latest fixes that - https://github.com/jenkins-x/terraform-aws-eks-jx/blob/master/modules/vault/charts.tf). We migrated from google to github for storing artifacts (docker images, helm charts etc ...)

**Comment by sidkris77** [comment]
Decided to go with another CI/CD provider in the end. A lot more plumbing involved. but at least thats documented.
