### ISSUE TITLE
CLI doesn't work after follow Doc's instructions

### ISSUE THREAD

**Issue by danielosg** [jenkins-x/jx-docs#3488]
After installing JX cli in Mac and Linux I always get the same error when running "jx help"

ERROR: failed to load plugin jx-help: can't find latest version of plugin: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-the-latest-release"}

I guess some step is missing.

**Comment by ankitm123** [comment]
There is no plugin named `jx-help` (probably some weird remains from previous install (?)), what u can do is remove the jx-help binary from the `~/.jx3/plugins/bin` folder, and then run jx plugin upgrade again.
I will add this to the documentation tonight.

**Comment by ankitm123** [comment]
Also, there is no jx help command, it's `jx --help`

**Comment by danielosg** [comment]
Ok, thanks then the Doc need just a minor update
![image](https://user-images.githubusercontent.com/72084247/144085820-f6451509-6c02-48b8-8689-9b77aca461b3.png)

**Comment by danielosg** [comment]
PR created https://github.com/jenkins-x/jx-docs/pull/3489
