### ISSUE TITLE
Error jx-webhook - Installation

### ISSUE THREAD

**Issue by Renanh** [jenkins-x/jx-docs#3494]
I've made several attempts to correctly create this, but it continues to show these errors, I loved the tool but the bad documentation is worrying, how to use with istio for example. need more risk details in the documentation for development. So no one will have the courage to put it in production, I agree it's fantastic but it's failing for the basics I think.

Even the video demonstrating performs in a different way than what is inscribed, let's make more educational videos with Istio, SonarQube,

![image](https://user-images.githubusercontent.com/8283925/145322863-6b471f96-2b5e-455f-8575-0c2924a2ce0e.png)

**Comment by ankitm123** [comment]
This is a known issue with kuberhealthy checks with Jenkins X, u can ignore it for now ... are there other issues apart from this one?

**Comment by ankitm123** [comment]
/close
closing this as I think this was resolved here and in slack.
