### ISSUE TITLE
switch to docsy go module

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx-docs#3516]
**This is a Feature Request**

https://github.com/google/docsy/discussions/535

Switch to go modules for docsy instead of git submodules.

**Comment by aabhas-sao** [comment]
Hey @ankitm123,

I find this issue interesting and would like to work on it. 
I found this article on how to migrate to the module.
https://deploy-preview-802--docsydocs.netlify.app/docs/updating/convert-site-to-module/

**Comment by ankitm123** [comment]
> Hey @ankitm123,
> 
> I find this issue interesting and would like to work on it. I found this article on how to migrate to the module. https://deploy-preview-802--docsydocs.netlify.app/docs/updating/convert-site-to-module/

Sgtm
