### ISSUE TITLE
Fix the margin in homepage

### ISSUE THREAD

**Issue by rajatgupta24** [jenkins-x/jx-docs#3522]
**This is a Bug Report**
Content getting clipped in mobile view

**Problem:**
![image](https://user-images.githubusercontent.com/55191777/151655307-e47d3efc-788c-451f-a426-d1eba676cca2.png)

**Proposed Solution:**
![image](https://user-images.githubusercontent.com/55191777/151655336-7348d5a7-3abf-4546-b61a-87983ff7fa65.png)

**Page to Update:**
https://jenkins-x.io/docs/....

**Steps to Reproduce:**

**Comment by ankitm123** [comment]
Known issue for some, would you like to make a contribution to fix this? The other thing is we dont have sidebar in mobile view.

**Comment by rajatgupta24** [comment]
Sure, I'll get on with it
