### ISSUE TITLE
Changing footer layout & adding new links

### ISSUE THREAD

**Issue by rajatgupta24** [jenkins-x/jx-docs#3535]
**This is a Feature Request**
Changing footer layout & adding new links

**What would you like to be added**

![image](https://user-images.githubusercontent.com/55191777/153215131-a2870a5c-68ba-4f58-b291-ad8c2bbafece.png)

**Why is this needed**
It looks a bit clean

**Comments**

**Comment by ankitm123** [comment]
Agreed, looks cleaner!
