### ISSUE TITLE
Broken links in content/en/v3/admin/platforms/on-premises/_index.md

### ISSUE THREAD

**Issue by rebelopsio** [jenkins-x/jx-docs#3551]
**This is a Bug Report**

**Problem:** 

Currently there are two broken links to guides that are hosted externally but are no longer accessible. The links both point to the same domain and return a 503.

Both links reside in file `content/en/v3/admin/platforms/on-premises/_index.md`.

First one:
https://github.com/jenkins-x/jx-docs/blob/38107f864abbe8f123a8ffffb9dab73c0d079ae5/content/en/v3/admin/platforms/on-premises/_index.md#L32

Second one:
https://github.com/jenkins-x/jx-docs/blob/38107f864abbe8f123a8ffffb9dab73c0d079ae5/content/en/v3/admin/platforms/on-premises/_index.md#L44

**Proposed Solution:**

Remove them for now or link them to different URLs/guides if available. 

**Page to Update:**

https://jenkins-x.io/v3/admin/platforms/on-premises/

**Steps to Reproduce:**

Go to the link above and click on either of the following links in the snippets:

>Here are some detailed [instructions](https://007ba7.us/howto/jx-install/) on getting JX running in a Lab Environment.

>If you are going the bare metal route you could try [these instructions](https://007ba7.us/howto/k8s-install/)

**Comment by ankitm123** [comment]
Is that web server down (007ba7.us)? It is probably a good idea to not to link to external blogs, and instead use official kubernetes documentation, so something like this: https://kubernetes.io/docs/setup/#production-environment would make more sense.

**Comment by rebelopsio** [comment]
@ankitm123 yes it appears to be down. I let this issue sit for a bit before opening a PR, but it's remained down. I have a PR currently open to remove the links since I didn't have a resource to replace them. See #3555. 

If you think it would be better to replace the broken links, I can update and point to the official docs you linked.

**Comment by rebelopsio** [comment]
@ankitm123 Also, the first link (same domain) references a tutorial for installing JX in a lab environment, which I don't have an official Jenkins X link to replace that one with.

**Comment by ankitm123** [comment]
I think for now, we can remove them. If we come across better links, we can add them back imo.

**Comment by rebelopsio** [comment]
Sounds good! Thanks @ankitm123

**Comment by ankitm123** [comment]
merged, thanks for the PR :100: 
/close
