### ISSUE TITLE
Some jx commands are unavailable

### ISSUE THREAD

**Issue by Chabouchakour** [jenkins-x/jx-docs#3557]
Installed jx via the documentation on linux. First of all, jx version --short doesn't work (only js version). In addition to that, while trying a lot of commands like jx boot I get failed to load plugin. Would appreciate the help, thank's.

**Comment by ankitm123** [comment]
Which docs did you follow? Seems like u saw the v2 docs. This is for v3: https://jenkins-x.io/v3/admin/setup/jx3/

**Comment by Chabouchakour** [comment]
First time followed the v2 but then I followed this one and still "jx boot" and "jx install" and other commands don't work.

**Comment by Chabouchakour** [comment]
Here is the error I get:
ERROR: failed to load plugin jx-boot: can't find latest version of plugin: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-the-latest-release"}

**Comment by ankitm123** [comment]
there is no jx boot and jx install anymore, those are v2 sub commands.
If you are trying to install jx on a cluster, use the admin guide for the desired platform: https://jenkins-x.io/v3/admin/platforms/
