### ISSUE TITLE
How is helpful. you are clearly between version 2 and 3 and there is no clear instructions on what works and what is a dead end. 

### ISSUE THREAD

**Issue by blackjack-jx-1** [jenkins-x/jx-docs#3562]

**Comment by ankitm123** [comment]
v2 is not maintained anymore, we have a banner on all v2 docs, saying users to use v3.
I am making a change now to make that even more clear.
Let us know if that helps.

**Comment by ankitm123** [comment]
Also, if there are any documents related to v2 which dont have that banner, please post it in this issue, and I will take care of it.

**Comment by ankitm123** [comment]
Going to close, as I think it's pretty clear from the docs that v2 is unsupported.
