### ISSUE TITLE
Too little localization（CN）

### ISSUE THREAD

**Issue by xiao-jay** [jenkins-x/jx-docs#3579]
- [x] read Localization_Chinese.md

i found readme and docs(v3) are not translate to Chinese, i am willing to translate it.

postscript: I am a junior from Hangzhou Dianzi University,tring to learn more about community,but i konw nothing，so i think translate is a easy and meaningful way to join it.

**Comment by ankitm123** [comment]
Hi @xiao-jay , that would be awesome!
Only the readme in english is up to date.

**Comment by LinuxSuRen** [comment]
Hi @xiao-jay , So glad to see you are willing to help us. That is great!

**Comment by xiao-jay** [comment]
hello，@LinuxSuRen, 
i've been a little busy lately, so i think i will translate a page every week.Does this issue  need to be keep open or will be closed and opened on my next contribute?
for example: [Docs-About-Jenkins](https://jenkins-x.io/v3/about/what/) is a page.

**Comment by LinuxSuRen** [comment]
> Does this issue need to be keep open or will be closed and opened on my next contribute?

IMO, it's not necessary to create an issue for each translation.
