### ISSUE TITLE
Team documentation is missing

### ISSUE THREAD

**Issue by ascheman** [jenkins-x/jx-docs#402]
Running `jx team --help` tells me I can find more information at https://jenkins-x.io/about/features/#teams - Unfortunately there is no such information in the docs.

**Comment by jtnord** [comment]
@ascheman can this be closed now that the is a section about teams?

**Comment by sharepointoscar** [comment]
I think this can be closed.  Though we do plan to add specific tutorials on using Teams in Jenkins X
