### ISSUE TITLE
create git server fail

### ISSUE THREAD

**Issue by jinjie2088** [jenkins-x/jx-docs#985]
[root@host-10-0-251-228 ~]# jx create git server -k github -u http://10.0.250.70:8088 -n localgit
Added Git server localgit for URL http://10.0.250.70:8088
error: Failed to create GitService with name : GitService.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required

what mean?

**Comment by LinuxSuRen** [comment]
I suggest you create the usage issues for jx in https://github.com/jenkins-x/jx. This repo is just documents.
